tasks:
  - init: |
      pip install -r requirements.txt
      (mkdir -p build/repos && cd build/repos && git clone https://github.com/leanprover-community/mathlib)
    command: |
      python make_html.py
      cd build/html && python -m http.server
